[docker-compose] Support different paths

diff --git a/home/bin/docker-compose b/home/bin/docker-compose
--- a/home/bin/docker-compose
+++ b/home/bin/docker-compose
@@ -1,2 +1,13 @@
 #!/bin/bash
-exec sudo /usr/bin/docker-compose "$@"
+ps=(
+	/usr/bin/docker-compose
+	/usr/local/bin/docker-compose
+)
+for p in "${ps[@]}"; do
+	if [ -x "$p" ]; then
+		exec sudo "$p" "$@"
+	fi
+done
+
+echo "docker-compose not found" >&2
+exit 1
